### ISSUE TITLE
Error waktu scan barcode

### ISSUE THREAD

**Issue by okazakicommunity** [Zero-YT7/BaseNew-ZeroYT7#5]
node:internal/errors:464
    ErrorCaptureStackTrace(err);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "key" argument must be of type string or an instance of ArrayBuffer, Buffer, TypedArray, DataView, KeyObject, or CryptoKey. Received undefined
    at new NodeError (node:internal/errors:371:5)
    at prepareSecretKey (node:internal/crypto/keys:570:11)
    at Cipheriv.createCipherWithIV (node:internal/crypto/cipher:133:9)
    at new Cipheriv (node:internal/crypto/cipher:243:3)
    at Object.createCipheriv (node:crypto:138:10)
    at Object.aesEncrypt (C:\Users\Arata\Base-ZeroYT7\node_modules\@adiwajshing\baileys\lib\WAConnection\Utils.js:108:24)
    at WAConnection.sendBinary (C:\Users\Arata\Base-ZeroYT7\node_modules\@adiwajshing\baileys\lib\WAConnection\0.Base.js:321:26)
    at WAConnection.<anonymous> (C:\Users\Arata\Base-ZeroYT7\node_modules\@adiwajshing\baileys\lib\WAConnection\4.Events.js:86:18)
    at WAConnection.emit (node:events:402:35)
    at WAConnection.emit (C:\Users\Arata\Base-ZeroYT7\node_modules\@adiwajshing\baileys\lib\WAConnection\4.Events.js:664:41) {
  code: 'ERR_INVALID_ARG_TYPE'
}

C:\Users\Arata\Base-ZeroYT7>

**Comment by ghost** [comment]
Leave from Multi-Device beta program on WhatsApp
